### ISSUE TITLE
noob needs help - Browserless Chromium token?

### ISSUE THREAD

**Issue by jkerekes99** [BJReplay/ha-sew-water#3]
Hi,
I am following the instructions to setup the South East Water metering as I have just had one installed.

I can at the stage of setting up the automation yaml and it says to paste the Browserless URL and Token.
I've got the URL, **but how do I get the token?**

**Comment by BJReplay** [comment]
When you configure browserless, you specify the token - I think either in the Docker compose or the environment file. I can't check now as I am away from home for the next couple of weeks.

Check out the installation instructions for browserless.

**Comment by jkerekes99** [comment]
Thanks for the reply @BJReplay.

I followed the instructions on this Github and installed browserless as a HASS Add-on.
So I don't have control of the docker compose or environment file because its managed in HASS.

These are the only settings I get:
![Image](https://github.com/user-attachments/assets/0d925963-c4df-4396-a8f8-cb22e12a2e46)

**Comment by jkerekes99** [comment]
No worries @BJReplay I tried to leave it blank, but when the automation tried to run I got this error which I dont think is related:

Action pyscript.force_water_state not found

Looking at your repo, I don't see any file named "force_water_state".
Am I missing something?

**Comment by BJReplay** [comment]
Oh, that's on me, sorry. I must have committed some but not all changes to try to make the script more robust.

Please leave this issue open, and I will attend to it when I get back home.

Welcome, thanks for reporting the problem, and hopefully you will be able to get up and running.

The good news is that I now have a pretty robust automation running, at last, that mostly copes well with South East Water's website.

The only thing that trips it up is sometimes the water meter does not record any data at all for a day.

But, apart from that, it now can start on your installation date, and track forward day by day to yesterday (provided that there are no days with no water consumption) and keep the data in HA up to date.

**Comment by jkerekes99** [comment]
No worries @BJReplay, I appreciate the work you have done, I don't have the skills to do this on my own.

Will leave the issue open and hopefully when you get a chance you can fix the code and let me know.

Cheers

**Comment by jkerekes99** [comment]
Hey @BJReplay .

I followed your instructions on the repo page word for word.
The instructions say to install the pyscript integration via HACS.

It doesn't say anything about configuring the integration.
What do I need to configure?

**Comment by jkerekes99** [comment]
Hey @BJReplay , thanks for your suggestion.

I don't get any more errors and I have let it run for the last week, but every day my data in the helper is "Unavailable" or 0L.

When I log into the South East Water website and go to the usage tab, it always shows blank for the last two days, and then there is data.

Does this show the same for you?
Does your integration / scraping account for this?

**Comment by BJReplay** [comment]
Yes, this isn't live - it depends on south east water reading the meter.

The website lags reality by one or two days, usually.

As of now, I have water readings for the 3rd, but nothing since.

The automation will run later today and try to get new readings.

**Comment by BJReplay** [comment]
Hi @jkerekes99 this automation can't do more than load the data from South East Water.  If I log in today, South East Water shows data for the 3rd of July, but not the 4th.

The automation downloads data for the 3rd, and keeps trying for the 4th.  When data is available, it will download it.

Occasionally South East Water will miss a day, and then have readings for the next day.  

When this happens, you'll need to manually set the `input_datetime.last_water_date` to the day that has no data (the day before South East Water has readings again), and the automation will then pick up readings.

But it sounds like you've got it working exactly as expected - it keeps the data in HA up to date with the website.

I'll update the readme when I have a chance - when I'm not working flat out seven days a week.

**Comment by jkerekes99** [comment]
But the issue is, my helper has no data whatsoever, not even past days:
![Image](https://github.com/user-attachments/assets/090e5489-25bb-473f-9028-04d3a84c8977)

If the SEW website has data for those days, shouldn't the data also be in the helper?

**Comment by BJReplay** [comment]
Depending on when you have your automation set up to run, about a minute or two after it runs, with any luck.

**Comment by BJReplay** [comment]
> Found this in the log:

@jkerekes99 thanks - that's the clue.

There's a step in the automation that is supposed to deal with that:


``` yaml
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: sensor.current_water_mains_usage
                  state: unavailable
                - condition: state
                  entity_id: sensor.current_water_mains_usage
                  state: unknown
              alias: If Water Usage Mains not set
          then:
            - action: pyscript.force_water_state
              data:
                stat_id: sensor.water_usage_mains
                tally: 0
              alias: Initialise Water Usage Mains
          alias: If Water Usage Mains not set, Initialise Water Usage Mains
```

Go to Developer Tools 

<img width="259" height="62" alt="Image" src="https://github.com/user-attachments/assets/e3fd240a-3509-467c-96dc-85b1dbc8b60b" />

Paste in 

``` yaml
action: pyscript.force_water_state
data:
  stat_id: sensor.water_usage_mains
  tally: 0
```

Click on Perform Action once and once only (it resets the total to 0.)

<img width="1002" height="469" alt="Image" src="https://github.com/user-attachments/assets/f76d8a43-4ee3-4ad1-a77a-8e63cc279935" />
